version: '3.8'
services:
  payment-db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres-volume:

networks:
  payment:
    name: payment