CREATE SEQUENCE IF NOT EXISTS MERCHANT_ID_SEQ;

CREATE SEQUENCE IF NOT EXISTS PAYMENT_ID_SEQ;

CREATE TABLE IF NOT EXISTS MERCHANT
(
    ID   BIGSERIAL
        PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PAYMENT
(
    ID                 BIGSERIAL
        PRIMARY KEY,
    AMOUNT             DOUBLE PRECISION           NOT NULL,
    CREATION_DATE      TIMESTAMP,
    CREDIT_CARD_NUMBER VARCHAR(255),
    CUSTOMER_NAME      VARCHAR(255),
    EXPIRY_DATE        VARCHAR(255),
    FEE                DOUBLE PRECISION DEFAULT 0 NOT NULL,
    REFERENCE_ID       BIGINT,
    STATUS             VARCHAR(255),
    MERCHANT_ID        BIGINT
        CONSTRAINT FKGI8GWSTWXKVP33LIY8GUN03HS
            REFERENCES MERCHANT
);

INSERT INTO MERCHANT (ID, NAME)
VALUES (1000, 'AMAZON');

INSERT INTO MERCHANT (ID, NAME)
VALUES (1001, 'TEMU');